# Generated by Django 4.2.29 on 2026-03-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="like",
            constraint=models.UniqueConstraint(
                fields=("user", "post"), name="unique_user_post_like"
            ),
        ),
    ]
